"""KALESS Engine — Docx Generator.

Produces formal academic reports using python-docx and Matplotlib for charts.
"""
import io
import os
from docx import Document
from docx.shared import Inches, Pt
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn
from docx.oxml import OxmlElement

from app.export.pdf_generator import _generate_matplotlib_chart

def set_cell_border(cell, **kwargs):
    """Set cell borders in python-docx table."""
    tc = cell._tc
    tcPr = tc.get_or_add_tcPr()
    tcBorders = OxmlElement('w:tcBorders')
    for edge in ('top', 'left', 'bottom', 'right', 'insideH', 'insideV'):
        edge_data = kwargs.get(edge)
        if edge_data:
            tag = 'w:{}'.format(edge)
            element = OxmlElement(tag)
            for key in ["sz", "val", "color", "space", "shadow"]:
                if key in edge_data:
                    element.set(qn('w:{}'.format(key)), str(edge_data[key]))
            tcBorders.append(element)
    tcPr.append(tcBorders)

def generate_docx(result: dict) -> bytes:
    """Generate an APA-formatted Docx from a NormalizedResult dictionary."""
    doc = Document()
    
    # Define styles
    style = doc.styles['Normal']
    font = style.font
    font.name = 'Times New Roman'
    font.size = Pt(12)
    
    # 1. Title
    title = doc.add_heading('KALESS Statistics Report', 0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    
    doc.add_paragraph(f"Analysis: {result.get('title', 'Statistical Analysis')}").bold = True
    
    var_str = ", ".join([f"{k}: {v}" for k, v in result.get("variables", {}).items()])
    doc.add_paragraph(f"Variables: {var_str}")
    
    # 2. Iterate Output Blocks
    blocks = result.get("output_blocks", [])
    
    for block in blocks:
        b_type = block.get("block_type")
        b_title = block.get("title", "")
        content = block.get("content", {})
        
        if b_type == "table":
            doc.add_heading(b_title, level=2)
            
            columns = content.get("columns", [])
            rows = content.get("rows", [])
            
            if not columns or not rows:
                continue
                
            table = doc.add_table(rows=len(rows) + 1, cols=len(columns))
            table.style = 'Normal Table'
            table.autofit = True
            
            # Header
            hdr_cells = table.rows[0].cells
            for idx, col in enumerate(columns):
                hdr_cells[idx].text = str(col)
                hdr_cells[idx].paragraphs[0].runs[0].bold = True
                set_cell_border(hdr_cells[idx], top={"sz": 12, "val": "single", "color": "000000"}, bottom={"sz": 12, "val": "single", "color": "000000"})
                
            # Rows
            for r_idx, row_data in enumerate(rows):
                row_cells = table.rows[r_idx + 1].cells
                for c_idx, col in enumerate(columns):
                    row_cells[c_idx].text = str(row_data.get(col, ""))
                    if r_idx == len(rows) - 1:
                        set_cell_border(row_cells[c_idx], bottom={"sz": 12, "val": "single", "color": "000000"})
            
            # Footnotes
            footnotes = content.get("footnotes", [])
            for fn in footnotes:
                p = doc.add_paragraph(f"Note. {fn}")
                p.runs[0].italic = True
                
        elif b_type == "chart":
            doc.add_heading(b_title, level=2)
            
            chart_type = content.get("chart_type", "bar")
            data = content.get("data", [])
            config = content.get("config", {})
            
            try:
                img_buf = _generate_matplotlib_chart(chart_type, data, config)
                doc.add_picture(img_buf, width=Inches(5.5))
            except Exception as e:
                doc.add_paragraph(f"[Chart generation failed: {str(e)}]")
                
        elif b_type == "text":
            doc.add_heading(b_title, level=2)
            doc.add_paragraph(content.get("text", ""))
            
    # 3. Interpretation (APA write-up)
    interp = result.get("interpretation")
    if interp and interp.get("academic_sentence"):
        doc.add_heading("Reporting (APA Style)", level=2)
        p = doc.add_paragraph(interp.get("academic_sentence", ""))
        p.paragraph_format.first_line_indent = Inches(0.5)
        p.paragraph_format.line_spacing = 2.0
        
    # 4. Metadata Footer
    meta = result.get("metadata", {})
    doc.add_paragraph(f"Generated by KALESS Engine on {meta.get('timestamp', 'Unknown Date')}")
    
    buffer = io.BytesIO()
    doc.save(buffer)
    return buffer.getvalue()
