"""KALESS Engine — PDF Generator.

Produces formal academic reports using ReportLab.
"""
import io
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle

def generate_pdf(result: dict) -> bytes:
    """Generate an A4 PDF from a NormalizedResult dictionary."""
    buffer = io.BytesIO()
    
    # Setup Document
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=50,
        leftMargin=50,
        topMargin=50,
        bottomMargin=50,
    )
    
    styles = getSampleStyleSheet()
    title_style = styles["Heading1"]
    h2_style = styles["Heading2"]
    normal_style = styles["Normal"]
    
    # Custom tight style for interpretation
    interp_style = ParagraphStyle(
        "Interpretation",
        parent=styles["Normal"],
        fontSize=11,
        leading=16,
        spaceAfter=14
    )
    
    story = []
    
    # 1. Title
    story.append(Paragraph(result.get("title", "Statistical Analysis Report"), title_style))
    story.append(Spacer(1, 12))
    
    # Metadata
    var_str = ", ".join([f"{k}: {v}" for k, v in result.get("variables", {}).items()])
    story.append(Paragraph(f"<b>Variables:</b> {var_str}", normal_style))
    story.append(Spacer(1, 12))
    
    # 2. Interpretation
    interp = result.get("interpretation")
    if interp:
        story.append(Paragraph("<b>APA Interpretation:</b>", normal_style))
        story.append(Spacer(1, 6))
        story.append(Paragraph(interp.get("academic_sentence", ""), interp_style))
        
        story.append(Paragraph("<b>Plain English:</b>", normal_style))
        story.append(Spacer(1, 6))
        story.append(Paragraph(interp.get("statistical_sentence", ""), interp_style))
        if interp.get("practical_sentence"):
            story.append(Paragraph(interp.get("practical_sentence", ""), interp_style))
    
    # 3. Tables Rendering Helpers
    def _build_table(data_matrix, title):
        story.append(Paragraph(title, h2_style))
        story.append(Spacer(1, 6))
        
        t = Table(data_matrix)
        t.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), colors.HexColor("#F1F4F8")),
            ('TEXTCOLOR', (0,0), (-1,0), colors.HexColor("#4B5E76")),
            ('ALIGN', (0,0), (-1,-1), 'LEFT'),
            ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
            ('BOTTOMPADDING', (0,0), (-1,0), 10),
            ('BACKGROUND', (0,1), (-1,-1), colors.white),
            ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor("#E5E9F0")),
            ('FONTSIZE', (0,0), (-1,-1), 9),
        ]))
        story.append(t)
        story.append(Spacer(1, 20))

    # 4. Descriptives
    desc = result.get("descriptives", [])
    if desc:
        matrix = [["Group", "N", "Mean", "SD", "SE"]]
        has_stats = False
        for d in desc:
            if "mean" in d:
                has_stats = True
            row = [
                d.get("group_name", ""),
                str(d.get("n", "")),
                f"{d['mean']:.3f}" if "mean" in d else "",
                f"{d['sd']:.3f}" if "sd" in d else "",
                f"{d['se']:.3f}" if "se" in d else ""
            ]
            matrix.append(row)
        if has_stats:
            _build_table(matrix, "Descriptive Statistics")
            
    # 5. Coefficients
    coefs = result.get("coefficients", [])
    if coefs:
        matrix = [["Variable", "B", "SE", "Beta", "t", "p-value", "95% CI"]]
        for c in coefs:
            b = f"{c['b']:.4f}"
            se = f"{c['se']:.4f}"
            beta = f"{c['beta']:.3f}" if c.get("beta") is not None else "-"
            t = f"{c['statistic']:.3f}"
            p = "< .001" if c["p_value"] < 0.001 else f"{c['p_value']:.4f}"
            ci = f"[{c['ci_lower']:.3f}, {c['ci_upper']:.3f}]"
            
            matrix.append([c["name"], b, se, beta, t, p, ci])
        _build_table(matrix, "Model Coefficients")
        
    # 6. Post Hoc
    ph = result.get("post_hoc", [])
    if ph:
        matrix = [["Comparison", "Mean Diff", "p-adj", "95% CI"]]
        for p in ph:
            comp = f"{p['group1']} vs {p['group2']}"
            diff = f"{p['mean_diff']:.3f}"
            padj = "< .001" if p["p_adjusted"] < 0.001 else f"{p['p_adjusted']:.4f}"
            if p.get("significant"):
                padj += "*"
            ci = f"[{p['ci_lower']:.3f}, {p['ci_upper']:.3f}]"
            matrix.append([comp, diff, padj, ci])
        _build_table(matrix, "Post-Hoc Comparisons")

    # 7. Metadata Footer
    story.append(Spacer(1, 30))
    meta = result.get("metadata", {})
    footer_text = f"Generated by KALESS Engine ({meta.get('library', 'Core')}) on {meta.get('timestamp', 'Unknown Date')}"
    story.append(Paragraph(f"<font color='gray' size='8'>{footer_text}</font>", normal_style))

    doc.build(story)
    
    return buffer.getvalue()
